# All about files and paths
# dir:
#   root: "bla"

# while loading yaml -> utf-8 is used in default
encoding: "utf-16"
# All for Logging stuff
logging:
  # Logfile shall look like prefix_date.log
  dir: "logs"
  logfile:
    date: "%Y%m%d%Hxx"
    prefix: 'log'
  format: '%(asctime)s - %(filename)s - %(levelname)s - %(message)s'
  datefmt: "%d.%m.%y %H:%M:%S"
  log_in_file: True
  log_in_stream: True
  loglevel_stream: info
  loglevel_file: debug

# All stuff to database and api request
database:
  base_url: 'https://api.geekdo.com/xmlapi2'
  dir: "data"
  db_file: "spiel.db"
  # Filename of json-File. If "None" no json is saved
  bgg_json: "plays.json"

# Specific Stuff on Homepage
www:
  ignored_users_name: ['Bot', 'Jörn', 'Quinn']
  ignored_boardgames_id: []
